// Original editorial drafts. Reviewer metadata is deliberately absent until review is complete.
export default [
{
uid:'data-licensing',
short:'Data licensing is an agreement that permits specified uses of a dataset under defined conditions. It can address access, AI training, sharing, payment, duration, and restrictions without necessarily transferring the underlying rights.',
definition:'Data licensing establishes the permission and conditions under which one party may use data supplied by another. A license might allow internal analysis, model training, or evaluation while excluding other uses. Its effect depends on the agreement and the rights the provider can actually grant; possessing a file does not establish unrestricted authority to license everything in it.',
how:'Start by identifying the dataset and the parties. A useful description states which systems and time periods are covered, what is excluded, how records will be delivered, and whether updates are included. The agreement then connects that description to permitted purposes, authorized users, security requirements, retention rules, and commercial terms.\n\nData licenses differ. For example, the Community Data License Agreement—Permissive 2.0 allows use, modification, and sharing subject to its terms and treats computational results separately. A negotiated commercial license may set different boundaries. Neither model should be assumed to apply before the actual agreement is examined.',
relevance:'For a business considering a license, the first question is what it can authorize. Customer agreements, employee information, third-party material, confidentiality duties, and privacy requirements can constrain the available scope. Separately, the recipient needs permission that fits the intended training or evaluation process.\n\nA discussion can begin with a description of systems, record types, approximate scale, and known restrictions. That avoids treating an initial commercial conversation as permission to transfer a production database. Pricing, exclusivity, downstream sharing, and treatment of model outputs should be considered explicitly rather than inferred from the word “license.”',
example:'Fictional example: A maintenance business considers supplying a defined set of equipment fault histories for model evaluation. The proposed agreement covers selected fields from a stated period, excludes technician contact details and customer contracts, limits recipients, and specifies deletion of the supplied files at the end of the evaluation. The parties separately address whether trained model artifacts may be retained. This is an illustration of possible terms, not a statement of Rancher’s standard agreement.',
limitations:'A license does not resolve every underlying legal obligation. Contract permission, copyright or database rights, privacy requirements, and confidentiality can overlap. Rights and exceptions vary by jurisdiction. A promise in an agreement also needs practical controls if it is to govern copies, access, and onward sharing.\n\nLicensing does not guarantee demand, an acceptable price, recurring revenue, or a dataset’s suitability for a particular model. Legal review should consider the proposed use and the actual records, not only the title of the agreement.',
questions:['Which records and rights can our business authorize, and which need separate permission?','Does the permitted use cover training, evaluation, derived datasets, and model artifacts?','Who can access or receive the data, and what happens when the agreement ends?'],
related:['licensing-scope','permitted-use','data-ownership','non-exclusive-licensing','third-party-data-rights'],sources:['wipo-license','cdla','oecd-sharing'],show_cta:true,
},
{
uid:'de-identification',
short:'De-identification is a process for reducing the association between data and identifiable people or organizations. It combines transformations and disclosure controls; removing names alone does not establish anonymity or eliminate re-identification risk.',
definition:'De-identification reduces the ability to connect records to the people or entities they describe. Depending on the data and intended access, it may involve removing direct identifiers, generalizing details, suppressing rare records, or changing how recipients can query information. It is a risk-management process whose effectiveness depends on context, rather than a universal label that makes a dataset safe for any use.',
how:'An assessment begins with the intended use, recipients, and information already available to them. Names and email addresses are direct identifiers, but dates, locations, uncommon events, and combinations of attributes can also reveal identity. Free-text notes, images, and linked tables require attention beyond a single list of sensitive columns.\n\nTechniques trade some information value for reduced disclosure risk. A team might replace exact dates with broader periods, remove an unusually identifying narrative, or provide access in a controlled environment instead of distributing files. NIST’s guidance recommends choosing a sharing model, setting measurable criteria, and testing disclosure risks. The documentation should record the transformations, assumptions, and residual limitations.',
relevance:'A prospective licensing arrangement should distinguish what has been transformed from what the recipient is permitted to do. Access controls, restrictions on linkage, onward-sharing rules, and retention limits may remain necessary after transformation. A description of the process is more useful than an unsupported assurance that data is “fully anonymous.”\n\nUnder the EU GDPR, pseudonymized information can still be personal data. Other jurisdictions and sector-specific rules use different tests. A qualified reviewer should determine which standard applies to the actual dataset and recipient context before disclosure.',
example:'Fictional example: A repair company removes customer names from job histories but notices that exact appointment times and rare equipment descriptions could identify a customer when combined with public posts. It broadens the dates, excludes unusually distinctive narratives, and tests whether the remaining information still supports the proposed task. The example does not establish that the resulting records meet any particular legal anonymity standard.',
limitations:'Masking visible identifiers is not the same as demonstrating sufficiently low disclosure risk. Keeping stable substitute IDs can preserve useful longitudinal patterns while also making linkage easier. Synthetic data can introduce its own leakage risks and is not automatically anonymous.\n\nRisk can change when additional datasets become available or when the audience expands. Review should therefore cover the release setting as well as the transformed values. De-identification also does not by itself establish ownership, permission to license, or compliance with every confidentiality obligation.',
questions:['Which direct and indirect identifiers occur in structured fields, attachments, and free text?','What outside information could a recipient use to link records back to individuals?','Which legal test, risk threshold, and access controls apply to this proposed disclosure?'],
related:['pseudonymization','anonymization','re-identification-risk','redaction','personally-identifiable-information'],sources:['nist-deid','gdpr','nist-pii'],show_cta:true,
},
{
uid:'computer-use-agent',
short:'A computer-use agent is an AI system that pursues a task by interacting with software interfaces, such as clicking controls, entering text, and moving between applications. Its actions need permissions, feedback, and checks against the intended outcome.',
definition:'A computer-use agent observes a computer interface and chooses actions intended to advance a task. It may work through screenshots, interface elements, keyboard input, or other tools. Unlike a system that only suggests instructions, it can change application state. That makes the surrounding permissions, stopping rules, and success checks part of the system’s practical design.',
how:'A typical interaction loop observes the current state, chooses an action, performs it, and checks the result. A task such as reconciling a spreadsheet with a service system may require many such steps and movement across applications. Some systems combine visual interaction with APIs; the label does not require every action to be a simulated mouse click.\n\nThe OSWorld benchmark illustrates evaluation in real computer environments using tasks with initial states and execution-based checks. A successful-looking screenshot is not necessarily evidence that the requested file, record, or setting was changed correctly. Evaluation needs to inspect the relevant outcome and account for side effects.',
relevance:'Business workflow records can describe the context, sequence, and outcomes of software-mediated work. For agent research, those details may help distinguish a meaningful demonstration from an isolated screenshot. Useful documentation can identify the application version, user role, starting state, actions, errors, and final result.\n\nSuch records may also expose customer information, credentials, employee activity, and third-party interfaces or content. A licensing assessment must address those constraints. The existence of a workflow log does not mean it is automatically suitable or authorized for agent training, and this definition does not claim that Rancher supplies any specific agent dataset.',
example:'Fictional example: An agent is asked to prepare a draft purchase request from an approved inventory report. It reads the report, enters item details in procurement software, checks the total, and stops before submission. A verifier confirms the draft contains the intended items and that no order was sent. A training record would need enough context to show both the authorized task and the boundary the agent respected.',
limitations:'Interface changes, ambiguous instructions, pop-ups, missing access, and unreliable observations can interrupt a task. An action that works in one software version may fail in another. Longer workflows also create more opportunities for errors to compound.\n\nBenchmark performance does not establish reliability on every business process. Production evaluation should test permissions, recovery, auditability, and unwanted actions alongside task completion. Human review can be required before consequential actions; the word “agent” is not a guarantee of safe autonomy.',
questions:['What was the starting state, and which actions was the operator authorized to take?','Can the intended outcome and unintended side effects be checked independently?','Do workflow records contain sensitive information or third-party material that must be excluded?'],
related:['ai-agents','workflow-trajectory','long-horizon-task','verifier','rl-environment'],sources:['osworld','gym'],show_cta:false,
}
];
